### ISSUE TITLE
error in running.....react-native-todo

### ISSUE THREAD

**Issue by kiranmonangi** [rishabhbhatia/react-native-todo#1]
$ npm start

> Todo@0.1.0 start C:\Users\monangi\Desktop\react-native-todo
> react-native-scripts start

'react-native-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Todo@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Todo@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\monangi\AppData\Roaming\npm-cache\_logs\2021-01-22T11_40_51_958Z-debug.log

**Comment by rishabhbhatia** [comment]
`npm WARN Local package.json exists, but node_modules missing, did you mean to install?` Try npm install, then run npm start.

refer to [Installing](https://github.com/rishabhbhatia/react-native-todo#clone--install)

**Comment by rishabhbhatia** [comment]
@kiranmonangi problem solved Kiran?

**Comment by rishabhbhatia** [comment]
closing this, feel free to reopen if you're still facing issues
